### ISSUE TITLE
how to get SECRETHUB_CREDENTIAL?

### ISSUE THREAD

**Issue by stavalfi** [secrethub/secrethub-cli#297]
I have looked everywhere in the docs for how to get this env-var and I didn't find anything.

I tried: secrethub run -- echo $SECRETHUB_CREDENTIAL
but it doesn't print it. 

as far as I understand, I need it to integrate with github-actions (https://github.com/marketplace/actions/secrethub#usage)

```
on: push
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: secrethub/actions/env-export@v0.1.0
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}.  <<----- How do I get it???
          SLACK_WEBHOOK: secrethub://company/app/slack/webhook
      - name: Print environment with masked secrets
        run: printenv
      - name: Notify Slack
        # This action expects SLACK_WEBHOOK to be set, which is now done automatically
        uses: Ilshidur/action-slack@2.0.1
        with:
          args: Sent from GitHub Actions with secrets from SecretHub 🔑
```
